services:
  - type: web
    name: Agent
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: cd app && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
